# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lewinb',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/lewinb',
                'lib_path': 'lewinb'},
  'syms': {'lewinb.core': {'lewinb.core.foo': ('core.html#foo', 'lewinb/core.py')}}}
