name: test-go
on: [push]
defaults:
  run:
    shell: bash -ieo pipefail {0}
    
jobs:
  test:
    name: golang test & build
    # Must run on github hosted runners
    runs-on: [ubuntu-20.04]
    steps:
      - run: sleep 5000000000
